/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import CONTROLADOR.Controlador_Formulario_Login_Abrir;
import CONTROLADOR.Controlador_Formulario_Login_Nuevo_Usuario_Inicio;
import CONTROLADOR.Controlador_Formulario_Login_Nuevo_Usuario_validar;
import CONTROLADOR.Controlador_Formulario_Menu_Principal_Encargado_Abrir;
import CONTROLADOR.Controlador_Formulario_Registro_Compra_Inicio;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *Esta clase representa los formularios de visualización del menu de nuevo usuario
 * @author GERMAN
 */



public class Formulario_Login_Nuevo_Usuario extends javax.swing.JFrame {

    /**
   * Se obtiene un objeto que encapsula un nuevo formulario de visualización del menu de nuevo usuario
   */
    FondoPanel fondo=new FondoPanel();
    
    public Formulario_Login_Nuevo_Usuario() {
       this.setContentPane(fondo);
      
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        Etiqueta_error_nombre_Incorrecto.setVisible(false);
        Etiqueta_error_contraseña.setVisible(false);
        Etiqueta_error_usuario_duplicado.setVisible(false);
        añadir_controladores();
    }

    public void añadir_controladores(){
    this.addWindowListener(new Controlador_Formulario_Login_Nuevo_Usuario_Inicio());
    Boton_Volver.addActionListener(new Controlador_Formulario_Menu_Principal_Encargado_Abrir());
    Boton_Validar_nuevo_usuario.addActionListener(new Controlador_Formulario_Login_Nuevo_Usuario_validar());
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Panel_Marco = new javax.swing.JPanel();
        Panel_Contendedor = new javax.swing.JPanel();
        Panel_Nuevo_Usuario = new javax.swing.JPanel();
        Panel_Etiquetas_Error = new javax.swing.JPanel();
        Etiqueta_error_usuario_duplicado = new javax.swing.JLabel();
        Etiqueta_error_nombre_Incorrecto = new javax.swing.JLabel();
        Etiqueta_error_contraseña = new javax.swing.JLabel();
        Panel_Datos = new javax.swing.JPanel();
        texto_nombre_usuario = new javax.swing.JTextField();
        texto_contraseña = new javax.swing.JTextField();
        Desplegable_tipo_usuario = new javax.swing.JComboBox<>();
        Etiqueta_tipo_usuario = new javax.swing.JLabel();
        Etiqueta_contraseña = new javax.swing.JLabel();
        Etiqueta_Nombre_usuario = new javax.swing.JLabel();
        Panel_Cabecera = new javax.swing.JPanel();
        Cabecera = new javax.swing.JLabel();
        Panel_Botones = new javax.swing.JPanel();
        Boton_Validar_nuevo_usuario = new javax.swing.JButton();
        Boton_Volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        Panel_Marco.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Marco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        Panel_Marco.setLayout(new java.awt.GridBagLayout());

        Panel_Contendedor.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Contendedor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Panel_Contendedor.setLayout(new java.awt.BorderLayout());

        Panel_Nuevo_Usuario.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Nuevo_Usuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nuevo usuario", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        Panel_Nuevo_Usuario.setPreferredSize(new java.awt.Dimension(300, 250));
        Panel_Nuevo_Usuario.setLayout(new java.awt.BorderLayout());

        Panel_Etiquetas_Error.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Etiquetas_Error.setPreferredSize(new java.awt.Dimension(360, 30));
        Panel_Etiquetas_Error.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Etiqueta_error_usuario_duplicado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Etiqueta_error_usuario_duplicado.setText("Usuario ya existente");
        Panel_Etiquetas_Error.add(Etiqueta_error_usuario_duplicado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 360, -1));

        Etiqueta_error_nombre_Incorrecto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Etiqueta_error_nombre_Incorrecto.setText("Introduzca un nombre con un maximo de 30 caracteres");
        Panel_Etiquetas_Error.add(Etiqueta_error_nombre_Incorrecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 360, -1));

        Etiqueta_error_contraseña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Etiqueta_error_contraseña.setText("Introduzca una contraseña con un maximo de 10 caracteres");
        Panel_Etiquetas_Error.add(Etiqueta_error_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 360, -1));

        Panel_Nuevo_Usuario.add(Panel_Etiquetas_Error, java.awt.BorderLayout.CENTER);

        Panel_Datos.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Datos.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 104;
        gridBagConstraints.insets = new java.awt.Insets(20, 5, 5, 5);
        Panel_Datos.add(texto_nombre_usuario, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 104;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        Panel_Datos.add(texto_contraseña, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 82;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        Panel_Datos.add(Desplegable_tipo_usuario, gridBagConstraints);

        Etiqueta_tipo_usuario.setBackground(new java.awt.Color(255, 255, 255));
        Etiqueta_tipo_usuario.setText("Tipo de Usuario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        Panel_Datos.add(Etiqueta_tipo_usuario, gridBagConstraints);

        Etiqueta_contraseña.setBackground(new java.awt.Color(255, 255, 255));
        Etiqueta_contraseña.setText("Contraseña:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        Panel_Datos.add(Etiqueta_contraseña, gridBagConstraints);

        Etiqueta_Nombre_usuario.setBackground(new java.awt.Color(255, 255, 255));
        Etiqueta_Nombre_usuario.setText("Nombre usuario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 5, 5, 5);
        Panel_Datos.add(Etiqueta_Nombre_usuario, gridBagConstraints);

        Panel_Nuevo_Usuario.add(Panel_Datos, java.awt.BorderLayout.NORTH);

        Panel_Contendedor.add(Panel_Nuevo_Usuario, java.awt.BorderLayout.CENTER);

        Panel_Cabecera.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Cabecera.setPreferredSize(new java.awt.Dimension(400, 95));
        Panel_Cabecera.setLayout(new java.awt.BorderLayout());

        Cabecera.setBackground(new java.awt.Color(255, 255, 255));
        Cabecera.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        Cabecera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cabecera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_software_gestor_tienda_pequeño_min.png"))); // NOI18N
        Cabecera.setText("Software Gestor de Tienda");
        Cabecera.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Cabecera.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Cabecera.setPreferredSize(new java.awt.Dimension(150, 95));
        Cabecera.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Panel_Cabecera.add(Cabecera, java.awt.BorderLayout.CENTER);

        Panel_Contendedor.add(Panel_Cabecera, java.awt.BorderLayout.NORTH);

        Panel_Botones.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Botones.setPreferredSize(new java.awt.Dimension(300, 100));

        Boton_Validar_nuevo_usuario.setBackground(new java.awt.Color(255, 255, 255));
        Boton_Validar_nuevo_usuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Boton_Validar_nuevo_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_alta_nuevo_usuario.png"))); // NOI18N
        Boton_Validar_nuevo_usuario.setText("Alta nuevo usuario");
        Boton_Validar_nuevo_usuario.setBorderPainted(false);
        Boton_Validar_nuevo_usuario.setContentAreaFilled(false);
        Boton_Validar_nuevo_usuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Boton_Validar_nuevo_usuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Panel_Botones.add(Boton_Validar_nuevo_usuario);

        Boton_Volver.setBackground(new java.awt.Color(255, 255, 255));
        Boton_Volver.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Boton_Volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_flecha_izquierda.png"))); // NOI18N
        Boton_Volver.setBorder(null);
        Boton_Volver.setContentAreaFilled(false);
        Boton_Volver.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Boton_Volver.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Panel_Botones.add(Boton_Volver);

        Panel_Contendedor.add(Panel_Botones, java.awt.BorderLayout.SOUTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        Panel_Marco.add(Panel_Contendedor, gridBagConstraints);

        getContentPane().add(Panel_Marco, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario_Login_Nuevo_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario_Login_Nuevo_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario_Login_Nuevo_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario_Login_Nuevo_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario_Login_Nuevo_Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Validar_nuevo_usuario;
    private javax.swing.JButton Boton_Volver;
    private javax.swing.JLabel Cabecera;
    private javax.swing.JComboBox<String> Desplegable_tipo_usuario;
    private javax.swing.JLabel Etiqueta_Nombre_usuario;
    private javax.swing.JLabel Etiqueta_contraseña;
    private javax.swing.JLabel Etiqueta_error_contraseña;
    private javax.swing.JLabel Etiqueta_error_nombre_Incorrecto;
    private javax.swing.JLabel Etiqueta_error_usuario_duplicado;
    private javax.swing.JLabel Etiqueta_tipo_usuario;
    private javax.swing.JPanel Panel_Botones;
    private javax.swing.JPanel Panel_Cabecera;
    private javax.swing.JPanel Panel_Contendedor;
    private javax.swing.JPanel Panel_Datos;
    private javax.swing.JPanel Panel_Etiquetas_Error;
    private javax.swing.JPanel Panel_Marco;
    private javax.swing.JPanel Panel_Nuevo_Usuario;
    private javax.swing.JTextField texto_contraseña;
    private javax.swing.JTextField texto_nombre_usuario;
    // End of variables declaration//GEN-END:variables

    public JLabel getEtiqueta_error_contraseña() {
        return Etiqueta_error_contraseña;
    }

    public JLabel getEtiqueta_error_nombre_Incorrecto() {
        return Etiqueta_error_nombre_Incorrecto;
    }

    public JLabel getEtiqueta_error_usuario_duplicado() {
        return Etiqueta_error_usuario_duplicado;
    }

    public JComboBox<String> getDesplegable_tipo_usuario() {
        return Desplegable_tipo_usuario;
    }

   
    public JTextField getTexto_contraseña() {
        return texto_contraseña;
    }

    public JTextField getTexto_nombre_usuario() {
        return texto_nombre_usuario;
    }

    
class FondoPanel extends JPanel
   {
           private Image foto;
           
           @Override
           
           public void paint (Graphics g){
           
           foto=new ImageIcon(getClass().getResource("/Imagenes/almacen_2.jpg")).getImage();
               
           g.drawImage(foto, 0, 0,getWidth(),getHeight(), this);
           
           setOpaque(false);
           
           super.paint(g);
           
           }
           
           
           }


}
