/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import CONTROLADOR.Controlador_Formulario_Cliente_Abrir;
import CONTROLADOR.Controlador_Formulario_Compras_Abrir;
import CONTROLADOR.Controlador_Formulario_Liquidacion_IVA_Abrir;
import CONTROLADOR.Controlador_Formulario_Login_Nuevo_Usuario_Abrir;
import CONTROLADOR.Controlador_Formulario_Menu_Principal_Encargado;
import CONTROLADOR.Controlador_Formulario_Proveedor_Abrir;
import CONTROLADOR.Controlador_Formulario_Ventas_Abrir;
import CONTROLADOR.Controlador_Formulario_Ver_Compras_Abrir;
import MODELO.Usuario;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JPanel;


/**
 *Esta clase representa los formularios de visualización del menu principal del encargado
 * @author GERMAN
 */



public class Formulario_Menu_Principal_Encargado extends javax.swing.JFrame {

    /**
   * Se obtiene un objeto que encapsula un nuevo formulario de visualización del menu principal del encargado
   */
    
    Usuario usuario;
    
    public Formulario_Menu_Principal_Encargado() {
        
        usuario=Usuario.getUsuario_en_curso();
        
        FondoPanel fondo=new FondoPanel();
        
        this.setContentPane(fondo);
        
        initComponents();
        
        this.setExtendedState(MAXIMIZED_BOTH);
        
        this.setLocationRelativeTo(null);
        Añadir_Controladores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Panel_Contendedor = new javax.swing.JPanel();
        Boton_Compras = new javax.swing.JButton();
        Boton_Productos = new javax.swing.JButton();
        Boton_Ventas = new javax.swing.JButton();
        Boton_proveedores = new javax.swing.JButton();
        Boton_Clientes = new javax.swing.JButton();
        Etiqueta_Menu_principal = new javax.swing.JLabel();
        Cabecera = new javax.swing.JLabel();
        Boton_IVA = new javax.swing.JButton();
        Panel_datos_usuario = new javax.swing.JPanel();
        Etiqueta_usuario = new javax.swing.JLabel();
        Etiqueta_Rol = new javax.swing.JLabel();
        Boton_Alta_Nuevo_Usuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 102, 255));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        Panel_Contendedor.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Contendedor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Panel_Contendedor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        java.awt.GridBagLayout Panel_ContendedorLayout = new java.awt.GridBagLayout();
        Panel_ContendedorLayout.columnWidths = new int[] {0, 7, 0, 7, 0, 7, 0, 7, 0};
        Panel_ContendedorLayout.rowHeights = new int[] {0, 17, 0, 17, 0, 17, 0, 17, 0, 17, 0, 17, 0, 17, 0};
        Panel_Contendedor.setLayout(Panel_ContendedorLayout);

        Boton_Compras.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Boton_Compras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_compras.png"))); // NOI18N
        Boton_Compras.setText("COMPRAS");
        Boton_Compras.setBorder(null);
        Boton_Compras.setBorderPainted(false);
        Boton_Compras.setContentAreaFilled(false);
        Boton_Compras.setFocusPainted(false);
        Boton_Compras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Boton_Compras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 87;
        gridBagConstraints.ipady = 32;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 50);
        Panel_Contendedor.add(Boton_Compras, gridBagConstraints);

        Boton_Productos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Boton_Productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_producto.png"))); // NOI18N
        Boton_Productos.setText("PRODUCTOS");
        Boton_Productos.setBorder(null);
        Boton_Productos.setContentAreaFilled(false);
        Boton_Productos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Boton_Productos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        Panel_Contendedor.add(Boton_Productos, gridBagConstraints);

        Boton_Ventas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Boton_Ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_ventas.png"))); // NOI18N
        Boton_Ventas.setText("VENTAS");
        Boton_Ventas.setBorder(null);
        Boton_Ventas.setContentAreaFilled(false);
        Boton_Ventas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Boton_Ventas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 97;
        gridBagConstraints.ipady = 32;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 50);
        Panel_Contendedor.add(Boton_Ventas, gridBagConstraints);

        Boton_proveedores.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Boton_proveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_proveedor.png"))); // NOI18N
        Boton_proveedores.setText("PROVEEDORES");
        Boton_proveedores.setBorder(null);
        Boton_proveedores.setContentAreaFilled(false);
        Boton_proveedores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Boton_proveedores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 63;
        gridBagConstraints.ipady = 32;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 50);
        Panel_Contendedor.add(Boton_proveedores, gridBagConstraints);

        Boton_Clientes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Boton_Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_cliente.png"))); // NOI18N
        Boton_Clientes.setText("CLIENTES");
        Boton_Clientes.setBorder(null);
        Boton_Clientes.setContentAreaFilled(false);
        Boton_Clientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Boton_Clientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.ipadx = 89;
        gridBagConstraints.ipady = 32;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 50);
        Panel_Contendedor.add(Boton_Clientes, gridBagConstraints);

        Etiqueta_Menu_principal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Etiqueta_Menu_principal.setForeground(new java.awt.Color(204, 0, 255));
        Etiqueta_Menu_principal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Etiqueta_Menu_principal.setText("Menú principal");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        Panel_Contendedor.add(Etiqueta_Menu_principal, gridBagConstraints);

        Cabecera.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        Cabecera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cabecera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_software_gestor_tienda_pequeño_min.png"))); // NOI18N
        Cabecera.setText("Software Gestor de Tienda");
        Cabecera.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Cabecera.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Cabecera.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        Panel_Contendedor.add(Cabecera, gridBagConstraints);

        Boton_IVA.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Boton_IVA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_ver_IVA.png"))); // NOI18N
        Boton_IVA.setText("IVA");
        Boton_IVA.setBorder(null);
        Boton_IVA.setBorderPainted(false);
        Boton_IVA.setContentAreaFilled(false);
        Boton_IVA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Boton_IVA.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.ipadx = 73;
        gridBagConstraints.ipady = 32;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 50);
        Panel_Contendedor.add(Boton_IVA, gridBagConstraints);

        Panel_datos_usuario.setBackground(new java.awt.Color(255, 255, 255));
        Panel_datos_usuario.setLayout(new java.awt.GridBagLayout());

        Etiqueta_usuario.setBackground(new java.awt.Color(255, 255, 255));
        Etiqueta_usuario.setText("Usuario: "+usuario.getNombre_usuario()
        );
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        Panel_datos_usuario.add(Etiqueta_usuario, gridBagConstraints);

        Etiqueta_Rol.setBackground(new java.awt.Color(255, 255, 255));
        Etiqueta_Rol.setText("Rol: Encargado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        Panel_datos_usuario.add(Etiqueta_Rol, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        Panel_Contendedor.add(Panel_datos_usuario, gridBagConstraints);

        Boton_Alta_Nuevo_Usuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Boton_Alta_Nuevo_Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_alta_nuevo_usuario_pequeño.png"))); // NOI18N
        Boton_Alta_Nuevo_Usuario.setText("Alta Nuevo Usuario");
        Boton_Alta_Nuevo_Usuario.setBorderPainted(false);
        Boton_Alta_Nuevo_Usuario.setContentAreaFilled(false);
        Boton_Alta_Nuevo_Usuario.setFocusPainted(false);
        Boton_Alta_Nuevo_Usuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Boton_Alta_Nuevo_Usuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        Panel_Contendedor.add(Boton_Alta_Nuevo_Usuario, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(50, 0, 0, 0);
        getContentPane().add(Panel_Contendedor, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Añadir_Controladores(){
    
        Controlador_Formulario_Menu_Principal_Encargado controlador=new Controlador_Formulario_Menu_Principal_Encargado();
        
        Boton_Compras.addActionListener(new Controlador_Formulario_Compras_Abrir());
        Boton_Ventas.addActionListener(new Controlador_Formulario_Ventas_Abrir());
        Boton_Productos.addActionListener(controlador);
        Boton_proveedores.addActionListener(new Controlador_Formulario_Proveedor_Abrir());
        Boton_IVA.addActionListener(new Controlador_Formulario_Liquidacion_IVA_Abrir());
        Boton_Clientes.addActionListener(new Controlador_Formulario_Cliente_Abrir());
        Boton_Alta_Nuevo_Usuario.addActionListener(new Controlador_Formulario_Login_Nuevo_Usuario_Abrir());
    };
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario_Menu_Principal_Encargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario_Menu_Principal_Encargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario_Menu_Principal_Encargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario_Menu_Principal_Encargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario_Menu_Principal_Encargado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Alta_Nuevo_Usuario;
    private javax.swing.JButton Boton_Clientes;
    private javax.swing.JButton Boton_Compras;
    private javax.swing.JButton Boton_IVA;
    private javax.swing.JButton Boton_Productos;
    private javax.swing.JButton Boton_Ventas;
    private javax.swing.JButton Boton_proveedores;
    private javax.swing.JLabel Cabecera;
    private javax.swing.JLabel Etiqueta_Menu_principal;
    private javax.swing.JLabel Etiqueta_Rol;
    private javax.swing.JLabel Etiqueta_usuario;
    private javax.swing.JPanel Panel_Contendedor;
    private javax.swing.JPanel Panel_datos_usuario;
    // End of variables declaration//GEN-END:variables

   class FondoPanel extends JPanel
   {
           private Image foto;
           
           @Override
           
           public void paint (Graphics g){
           
           foto=new ImageIcon(getClass().getResource("/Imagenes/almacen_2.jpg")).getImage();
               
           g.drawImage(foto, 0, 0,getWidth(),getHeight(), this);
           
           setOpaque(false);
           
           super.paint(g);
           
           }
           
           
           }


}
