/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;


import CONTROLADOR.Controlador_Fomulario_Login_Entrar;
import CONTROLADOR.Controlador_Formulario_Login_Texto_Contraseña;
import CONTROLADOR.Controlador_Formulario_Login_Nuevo_Usuario_Abrir;
import CONTROLADOR.Controlador_Formulario_Login_Texto_Usuario;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *Esta clase representa los formularios de visualización del menu de login
 * @author GERMAN
 */




public class Formulario_Login extends javax.swing.JFrame {

   /**
   * Se obtiene un objeto que encapsula un nuevo formulario de visualización del menu de login
   */
    public Formulario_Login() {
        
        initComponents();
        Panel_Contendedor.requestFocusInWindow();
        Etiqueta_error_usuario.setVisible(false);
        Etiqueta_error_contraseña.setVisible(false);
        
        this.setLocationRelativeTo(null);
        añadir_controladores();
        
        
    }
    
    public void añadir_controladores(){
    
  texto_usuario.addFocusListener(new Controlador_Formulario_Login_Texto_Usuario());
  texto_Contraseña_usuario.addFocusListener(new Controlador_Formulario_Login_Texto_Contraseña());
  Boton_entrar.addActionListener(new Controlador_Fomulario_Login_Entrar());
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Panel_Marco = new javax.swing.JPanel();
        Panel_Contendedor = new javax.swing.JPanel();
        Panel_Login = new javax.swing.JPanel();
        Panel_Campos = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        foto_usuario = new javax.swing.JLabel();
        foto_contraseña = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        texto_usuario = new javax.swing.JTextField();
        texto_Contraseña_usuario = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        Etiqueta_error_usuario = new javax.swing.JLabel();
        Etiqueta_error_contraseña = new javax.swing.JLabel();
        Panel_Botones = new javax.swing.JPanel();
        Boton_entrar = new javax.swing.JButton();
        Panel_Cabecera = new javax.swing.JPanel();
        Cabecera = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Panel_Marco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        Panel_Marco.setPreferredSize(new java.awt.Dimension(320, 335));
        Panel_Marco.setLayout(new java.awt.GridBagLayout());

        Panel_Contendedor.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Contendedor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Panel_Contendedor.setPreferredSize(new java.awt.Dimension(250, 335));
        Panel_Contendedor.setLayout(new java.awt.BorderLayout());

        Panel_Login.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Login.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        Panel_Login.setLayout(new java.awt.GridBagLayout());

        Panel_Campos.setPreferredSize(new java.awt.Dimension(199, 132));
        Panel_Campos.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        foto_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_usuario_login.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel1.add(foto_usuario, gridBagConstraints);

        foto_contraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_password_login.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel1.add(foto_contraseña, gridBagConstraints);

        Panel_Campos.add(jPanel1, java.awt.BorderLayout.WEST);

        jPanel2.setPreferredSize(new java.awt.Dimension(360, 64));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        texto_usuario.setText("Usuario");
        texto_usuario.setPreferredSize(new java.awt.Dimension(40, 20));
        texto_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto_usuarioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 244;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel2.add(texto_usuario, gridBagConstraints);

        texto_Contraseña_usuario.setText("Contraseña");
        texto_Contraseña_usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 244;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel2.add(texto_Contraseña_usuario, gridBagConstraints);

        Panel_Campos.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Etiqueta_error_usuario.setText("El usuario introducido no existe");
        Etiqueta_error_usuario.setOpaque(true);
        jPanel3.add(Etiqueta_error_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        Etiqueta_error_contraseña.setText("La contraseña es incorrecta");
        jPanel3.add(Etiqueta_error_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        Panel_Campos.add(jPanel3, java.awt.BorderLayout.SOUTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        Panel_Login.add(Panel_Campos, gridBagConstraints);

        Panel_Botones.setBackground(new java.awt.Color(255, 255, 255));

        Boton_entrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Boton_entrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_entrar_pequeño.png"))); // NOI18N
        Boton_entrar.setText("Entrar");
        Boton_entrar.setBorderPainted(false);
        Boton_entrar.setContentAreaFilled(false);
        Boton_entrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Boton_entrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Panel_Botones.add(Boton_entrar);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        Panel_Login.add(Panel_Botones, gridBagConstraints);

        Panel_Contendedor.add(Panel_Login, java.awt.BorderLayout.CENTER);

        Panel_Cabecera.setLayout(new java.awt.BorderLayout());

        Cabecera.setBackground(new java.awt.Color(255, 255, 255));
        Cabecera.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        Cabecera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cabecera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_software_gestor_tienda_pequeño_min.png"))); // NOI18N
        Cabecera.setText("Software Gestor de Tienda");
        Cabecera.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Cabecera.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Cabecera.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Panel_Cabecera.add(Cabecera, java.awt.BorderLayout.CENTER);

        Panel_Contendedor.add(Panel_Cabecera, java.awt.BorderLayout.NORTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 30, 30);
        Panel_Marco.add(Panel_Contendedor, gridBagConstraints);

        getContentPane().add(Panel_Marco, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texto_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_usuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_entrar;
    private javax.swing.JLabel Cabecera;
    private javax.swing.JLabel Etiqueta_error_contraseña;
    private javax.swing.JLabel Etiqueta_error_usuario;
    private javax.swing.JPanel Panel_Botones;
    private javax.swing.JPanel Panel_Cabecera;
    private javax.swing.JPanel Panel_Campos;
    private javax.swing.JPanel Panel_Contendedor;
    private javax.swing.JPanel Panel_Login;
    private javax.swing.JPanel Panel_Marco;
    private javax.swing.JLabel foto_contraseña;
    private javax.swing.JLabel foto_usuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField texto_Contraseña_usuario;
    private javax.swing.JTextField texto_usuario;
    // End of variables declaration//GEN-END:variables

    public JButton getBoton_entrar() {
        return Boton_entrar;
    }

    public JPasswordField getTexto_Contraseña_usuario() {
        return texto_Contraseña_usuario;
    }

    public JTextField getTexto_usuario() {
        return texto_usuario;
    }

    public JLabel getEtiqueta_error_contraseña() {
        return Etiqueta_error_contraseña;
    }

    public JLabel getEtiqueta_error_usuario() {
        return Etiqueta_error_usuario;
    }

}
