/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;


import CONTROLADOR.*;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;



/**
 *Esta clase representa los formularios de visualización de la liquidación del IVA
 * @author GERMAN
 */




public class Formulario_Liquidacion_IVA extends javax.swing.JFrame {

    FondoPanel fondo=new FondoPanel();
    /**
   * Se obtiene un objeto que encapsula un nuevo formulario de visualización de la liquidación del IVA
   */
    public Formulario_Liquidacion_IVA() {
        
        this.setContentPane(fondo);
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        añadir_controladores();
        
    }
    
    public void añadir_controladores(){
    this.addWindowListener(new Controlador_Formulario_Liquidacion_IVA_Inicio());
    Boton_Ver_Resultado_Liquidacion.addActionListener(new Controlador_Formulario_Liquidacion_IVA_Boton_Liquidacion_IVA());
    Boton_Volver.addActionListener(new Controlador_Formulario_Menu_Principal_Encargado_Abrir());
    
    
    }

    public JComboBox<String> getDesplegable_Trimestre() {
        return Desplegable_Trimestre;
    }

    public JComboBox<String> getDesplegable_año() {
        return Desplegable_año;
    }

    public JTable getTabla_IVA_Repercutido() {
        return Tabla_IVA_Repercutido;
    }

    public JTable getTabla_IVA_Soportado() {
        return Tabla_IVA_Soportado;
    }

    public JLabel getImporte_BI_Repercutido() {
        return Importe_BI_Repercutido;
    }

    public JLabel getImporte_BI_Soportado() {
        return Importe_BI_Soportado;
    }

    public JLabel getImporte_IVA_Repercutido() {
        return Importe_IVA_Repercutido;
    }

    public JLabel getImporte_IVA_Soportado() {
        return Importe_IVA_Soportado;
    }

    public JLabel getImporte_Liquidación() {
        return Importe_Liquidación;
    }

    public JLabel getTexto_Resultado_Liquidacion() {
        return Texto_Resultado_Liquidacion;
    }

    
    
    
    
  
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        Boton_Volver = new javax.swing.JButton();
        Panel_Periodo_Liquidacion = new javax.swing.JPanel();
        Desplegable_año = new javax.swing.JComboBox<>();
        Desplegable_Trimestre = new javax.swing.JComboBox<>();
        Boton_Ver_Resultado_Liquidacion = new javax.swing.JButton();
        Panel_IVA_Soportado = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_IVA_Soportado = new javax.swing.JTable();
        Etiqueta_Base_Imponible_Soportado = new javax.swing.JLabel();
        Etiqueta_IVA_Soportado = new javax.swing.JLabel();
        Importe_IVA_Soportado = new javax.swing.JLabel();
        Importe_BI_Soportado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Panel_IVA_Repercutido = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tabla_IVA_Repercutido = new javax.swing.JTable();
        Etiqueta_IVA_Repercutido = new javax.swing.JLabel();
        Importe_BI_Repercutido = new javax.swing.JLabel();
        Importe_IVA_Repercutido = new javax.swing.JLabel();
        Etiqueta_Base_Imponible_Repercutido = new javax.swing.JLabel();
        Panel_Resultado_Liquidacion = new javax.swing.JPanel();
        Importe_Liquidación = new javax.swing.JLabel();
        Texto_Resultado_Liquidacion = new javax.swing.JLabel();
        Panel_Cabecera = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Cabecera = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 102, 255));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 700));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        Boton_Volver.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Boton_Volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_flecha_izquierda.png"))); // NOI18N
        Boton_Volver.setBorder(null);
        Boton_Volver.setContentAreaFilled(false);
        Boton_Volver.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Boton_Volver.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(78, 280, 0, 0);
        jPanel1.add(Boton_Volver, gridBagConstraints);

        Panel_Periodo_Liquidacion.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Periodo_Liquidacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Periodo Liquidacion", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        Panel_Periodo_Liquidacion.setLayout(new java.awt.GridBagLayout());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        Panel_Periodo_Liquidacion.add(Desplegable_año, gridBagConstraints);

        Desplegable_Trimestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1º Trimestre", "2º Trimestre", "3º Trimestre", "4º Trimestre" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        Panel_Periodo_Liquidacion.add(Desplegable_Trimestre, gridBagConstraints);

        Boton_Ver_Resultado_Liquidacion.setBackground(new java.awt.Color(255, 255, 255));
        Boton_Ver_Resultado_Liquidacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_calcular.png"))); // NOI18N
        Boton_Ver_Resultado_Liquidacion.setText("Resultado Liquidación");
        Boton_Ver_Resultado_Liquidacion.setBorderPainted(false);
        Boton_Ver_Resultado_Liquidacion.setContentAreaFilled(false);
        Boton_Ver_Resultado_Liquidacion.setFocusPainted(false);
        Boton_Ver_Resultado_Liquidacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Boton_Ver_Resultado_Liquidacion.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Boton_Ver_Resultado_Liquidacion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Boton_Ver_Resultado_Liquidacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Ver_Resultado_LiquidacionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        Panel_Periodo_Liquidacion.add(Boton_Ver_Resultado_Liquidacion, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 248, 10, 0);
        jPanel1.add(Panel_Periodo_Liquidacion, gridBagConstraints);

        Panel_IVA_Soportado.setBackground(new java.awt.Color(255, 255, 255));
        Panel_IVA_Soportado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "IVA Soportado", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        Panel_IVA_Soportado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(225, 48));

        Tabla_IVA_Soportado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo IVA %", "Base Imponible €", "Importe IVA €"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla_IVA_Soportado.setAutoscrolls(false);
        Tabla_IVA_Soportado.setPreferredSize(new java.awt.Dimension(225, 48));
        jScrollPane1.setViewportView(Tabla_IVA_Soportado);
        if (Tabla_IVA_Soportado.getColumnModel().getColumnCount() > 0) {
            Tabla_IVA_Soportado.getColumnModel().getColumn(0).setResizable(false);
            Tabla_IVA_Soportado.getColumnModel().getColumn(1).setResizable(false);
            Tabla_IVA_Soportado.getColumnModel().getColumn(2).setResizable(false);
        }

        Panel_IVA_Soportado.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 300, 70));

        Etiqueta_Base_Imponible_Soportado.setText("Base imponible total:");
        Panel_IVA_Soportado.add(Etiqueta_Base_Imponible_Soportado, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 120, -1));

        Etiqueta_IVA_Soportado.setText("IVA soportado total:");
        Panel_IVA_Soportado.add(Etiqueta_IVA_Soportado, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        Importe_IVA_Soportado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Panel_IVA_Soportado.add(Importe_IVA_Soportado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 140, 10));

        Importe_BI_Soportado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Panel_IVA_Soportado.add(Importe_BI_Soportado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 140, 10));

        jLabel1.setText("                                                           ");
        Panel_IVA_Soportado.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, 20));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(160, 0, 20, 0);
        jPanel1.add(Panel_IVA_Soportado, gridBagConstraints);

        Panel_IVA_Repercutido.setBackground(new java.awt.Color(255, 255, 255));
        Panel_IVA_Repercutido.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "IVA Repercutido", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        Panel_IVA_Repercutido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane3.setPreferredSize(new java.awt.Dimension(225, 48));

        Tabla_IVA_Repercutido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo IVA %", "Base Imponible €", "Importe IVA €"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla_IVA_Repercutido.setAutoscrolls(false);
        Tabla_IVA_Repercutido.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Tabla_IVA_Repercutido.setPreferredSize(new java.awt.Dimension(225, 48));
        jScrollPane3.setViewportView(Tabla_IVA_Repercutido);
        if (Tabla_IVA_Repercutido.getColumnModel().getColumnCount() > 0) {
            Tabla_IVA_Repercutido.getColumnModel().getColumn(0).setResizable(false);
            Tabla_IVA_Repercutido.getColumnModel().getColumn(1).setResizable(false);
            Tabla_IVA_Repercutido.getColumnModel().getColumn(2).setResizable(false);
        }

        Panel_IVA_Repercutido.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 300, 70));

        Etiqueta_IVA_Repercutido.setText("IVA repercutido total:");
        Panel_IVA_Repercutido.add(Etiqueta_IVA_Repercutido, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        Importe_BI_Repercutido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Importe_BI_Repercutido.setPreferredSize(new java.awt.Dimension(0, 14));
        Panel_IVA_Repercutido.add(Importe_BI_Repercutido, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 130, 10));

        Importe_IVA_Repercutido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Panel_IVA_Repercutido.add(Importe_IVA_Repercutido, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 120, 10));

        Etiqueta_Base_Imponible_Repercutido.setText("Base imponible total:");
        Panel_IVA_Repercutido.add(Etiqueta_Base_Imponible_Repercutido, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 120, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 36;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(160, 0, 20, 0);
        jPanel1.add(Panel_IVA_Repercutido, gridBagConstraints);

        Panel_Resultado_Liquidacion.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Resultado_Liquidacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultado Liquidación", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        Panel_Resultado_Liquidacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Importe_Liquidación.setBackground(new java.awt.Color(153, 153, 255));
        Importe_Liquidación.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Importe_Liquidación.setPreferredSize(new java.awt.Dimension(20, 10));
        Panel_Resultado_Liquidacion.add(Importe_Liquidación, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 140, -1));

        Texto_Resultado_Liquidacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto_Resultado_Liquidacion.setPreferredSize(new java.awt.Dimension(20, 10));
        Panel_Resultado_Liquidacion.add(Texto_Resultado_Liquidacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 210, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 202, 0, 0);
        jPanel1.add(Panel_Resultado_Liquidacion, gridBagConstraints);

        Panel_Cabecera.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Cabecera.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Liquidacion IVA");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        Panel_Cabecera.add(jLabel2, gridBagConstraints);

        Cabecera.setBackground(new java.awt.Color(255, 255, 255));
        Cabecera.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        Cabecera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cabecera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_software_gestor_tienda_pequeño_min.png"))); // NOI18N
        Cabecera.setText("Software Gestor de Tienda");
        Cabecera.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Cabecera.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Cabecera.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Panel_Cabecera.add(Cabecera, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 222, 0, 0);
        jPanel1.add(Panel_Cabecera, gridBagConstraints);

        getContentPane().add(jPanel1, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_Ver_Resultado_LiquidacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Ver_Resultado_LiquidacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_Ver_Resultado_LiquidacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario_Liquidacion_IVA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario_Liquidacion_IVA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario_Liquidacion_IVA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario_Liquidacion_IVA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario_Liquidacion_IVA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Ver_Resultado_Liquidacion;
    private javax.swing.JButton Boton_Volver;
    private javax.swing.JLabel Cabecera;
    private javax.swing.JComboBox<String> Desplegable_Trimestre;
    private javax.swing.JComboBox<String> Desplegable_año;
    private javax.swing.JLabel Etiqueta_Base_Imponible_Repercutido;
    private javax.swing.JLabel Etiqueta_Base_Imponible_Soportado;
    private javax.swing.JLabel Etiqueta_IVA_Repercutido;
    private javax.swing.JLabel Etiqueta_IVA_Soportado;
    private javax.swing.JLabel Importe_BI_Repercutido;
    private javax.swing.JLabel Importe_BI_Soportado;
    private javax.swing.JLabel Importe_IVA_Repercutido;
    private javax.swing.JLabel Importe_IVA_Soportado;
    private javax.swing.JLabel Importe_Liquidación;
    private javax.swing.JPanel Panel_Cabecera;
    private javax.swing.JPanel Panel_IVA_Repercutido;
    private javax.swing.JPanel Panel_IVA_Soportado;
    private javax.swing.JPanel Panel_Periodo_Liquidacion;
    private javax.swing.JPanel Panel_Resultado_Liquidacion;
    private javax.swing.JTable Tabla_IVA_Repercutido;
    private javax.swing.JTable Tabla_IVA_Soportado;
    private javax.swing.JLabel Texto_Resultado_Liquidacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables

class FondoPanel extends JPanel
   {
           private Image foto;
           
           @Override
           
           public void paint (Graphics g){
           
           foto=new ImageIcon(getClass().getResource("/Imagenes/almacen_2.jpg")).getImage();
               
           g.drawImage(foto, 0, 0,getWidth(),getHeight(), this);
           
           setOpaque(false);
           
           super.paint(g);
           
           }
           
           
           }



}
