/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import CONTROLADOR.*;
import MODELO.*;
import static com.sun.java.accessibility.util.AWTEventMonitor.addWindowListener;
import com.toedter.calendar.JDateChooser;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *Esta clase representa los formularios de registro de ventas 
 * @author GERMAN
 */






public class Formulario_Registro_Venta extends javax.swing.JFrame {

    /**
   * Se obtiene un objeto que encapsula un nuevo formulario de registro de ventas 
   */
    
    FondoPanel fondo=new FondoPanel();
    
    
    
    private ArrayList lista_clientes= new ArrayList<Cliente>();
    
    private ArrayList lista_productos= new ArrayList<Producto>();
    
    
    
    public Formulario_Registro_Venta() {
        this.setContentPane(fondo);
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        Etiqueta_Error_fecha.setVisible(false);
        Etiqueta_Error_cantidad.setVisible(false);
        Etiqueta_Error_producto_duplicado.setVisible(false);
        Etiqueta_Error_no_seleccion.setVisible(false);
        Etiqueta_Error_Stock.setVisible(false);
        
        añadir_Controladores();
    }
    
    public void añadir_Controladores(){
    
    
    this.addWindowListener(new Controlador_Formulario_Registro_Venta_Inicio());
    
    Desplegable_Clientes.addActionListener(new Controlador_Formulario_Registro_Venta_Etiqueta_Cliente());
  
    Desplegable_Producto.addActionListener(new Controlador_Formulario_Registro_Venta_Etiqueta_Producto());
    
    Añadir_Producto.addActionListener(new Controlador_Formulario_Registro_Venta_Añade_Producto());
    
    Eliminar_producto.addActionListener(new Controlador_Formulario_Registro_Venta_Elimina_Producto());
    
    Boton_Volver.addActionListener(new Controlador_Formulario_Ventas_Abrir());
    
    Boton_Validar_Registro.addActionListener(new Controlador_Formulario_Registro_Venta_Validar_Venta());
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Panel_General = new javax.swing.JPanel();
        Etiqueta_venta = new javax.swing.JLabel();
        Boton_Volver = new javax.swing.JButton();
        Cabecera = new javax.swing.JLabel();
        Panel_Registro_Venta = new javax.swing.JPanel();
        Desplegable_Clientes = new javax.swing.JComboBox<>();
        JLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Etiqueta_Espacio = new javax.swing.JLabel();
        Etiqueta_Registro_Venta = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        Eliminar_producto = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Desplegable_Producto = new javax.swing.JComboBox<>();
        Campo_cantidad = new javax.swing.JTextField();
        Añadir_Producto = new javax.swing.JButton();
        Etiqueta_Cliente = new javax.swing.JLabel();
        Etiqueta_Producto = new javax.swing.JLabel();
        Etiqueta_Error_fecha = new javax.swing.JLabel();
        Etiqueta_Error_cantidad = new javax.swing.JLabel();
        Panel_Detalle_Venta = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable(){

            public boolean isCellEditable(int row, int column) {
                return false;
            }

        };
        Etiqueta_Error_producto_duplicado = new javax.swing.JLabel();
        Etiqueta_Error_no_seleccion = new javax.swing.JLabel();
        Etiqueta_Error_Stock = new javax.swing.JLabel();
        Espacio = new javax.swing.JLabel();
        Espacio1 = new javax.swing.JLabel();
        Panel_Importe_Compra = new javax.swing.JPanel();
        Boton_Validar_Registro = new javax.swing.JButton();
        Etiqueta_IVA = new javax.swing.JLabel();
        Etiqueta_base_imponible = new javax.swing.JLabel();
        Etiqueta_Total = new javax.swing.JLabel();
        Importe_Base_Imponible = new javax.swing.JLabel();
        Importe_IVA = new javax.swing.JLabel();
        Importe_Total = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 102, 255));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        Panel_General.setBackground(new java.awt.Color(255, 255, 255));
        Panel_General.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 6, 0, 6, 0};
        jPanel1Layout.rowHeights = new int[] {0, 18, 0, 18, 0, 18, 0, 18, 0, 18, 0};
        Panel_General.setLayout(jPanel1Layout);

        Etiqueta_venta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Etiqueta_venta.setForeground(new java.awt.Color(204, 0, 255));
        Etiqueta_venta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Etiqueta_venta.setText("Registro Venta");
        Etiqueta_venta.setPreferredSize(new java.awt.Dimension(40, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        Panel_General.add(Etiqueta_venta, gridBagConstraints);

        Boton_Volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_flecha_izquierda.png"))); // NOI18N
        Boton_Volver.setBorderPainted(false);
        Boton_Volver.setContentAreaFilled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        Panel_General.add(Boton_Volver, gridBagConstraints);

        Cabecera.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        Cabecera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cabecera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_software_gestor_tienda_pequeño_min.png"))); // NOI18N
        Cabecera.setText("Software Gestor de Tienda");
        Cabecera.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Cabecera.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Cabecera.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        Panel_General.add(Cabecera, gridBagConstraints);

        Panel_Registro_Venta.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Registro_Venta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro Venta", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        Panel_Registro_Venta.setPreferredSize(new java.awt.Dimension(520, 220));
        Panel_Registro_Venta.setLayout(new java.awt.GridBagLayout());

        Desplegable_Clientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", " ", " " }));
        Desplegable_Clientes.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 125;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        Panel_Registro_Venta.add(Desplegable_Clientes, gridBagConstraints);

        JLabel.setText("Cliente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        Panel_Registro_Venta.add(JLabel, gridBagConstraints);

        jLabel6.setText("Nº de Registro");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        Panel_Registro_Venta.add(jLabel6, gridBagConstraints);

        Etiqueta_Espacio.setText("                                                                                        ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        Panel_Registro_Venta.add(Etiqueta_Espacio, gridBagConstraints);

        Etiqueta_Registro_Venta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Etiqueta_Registro_Venta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Etiqueta_Registro_Venta.setText("Registro Venta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        Panel_Registro_Venta.add(Etiqueta_Registro_Venta, gridBagConstraints);

        jLabel8.setText("Fecha");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        Panel_Registro_Venta.add(jLabel8, gridBagConstraints);

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 124;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        Panel_Registro_Venta.add(jDateChooser1, gridBagConstraints);

        jLabel9.setText("Producto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        Panel_Registro_Venta.add(jLabel9, gridBagConstraints);

        Eliminar_producto.setText("Eliminar producto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        Panel_Registro_Venta.add(Eliminar_producto, gridBagConstraints);

        jLabel10.setText("Cantidad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        Panel_Registro_Venta.add(jLabel10, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 97;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        Panel_Registro_Venta.add(Desplegable_Producto, gridBagConstraints);

        Campo_cantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 86;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        Panel_Registro_Venta.add(Campo_cantidad, gridBagConstraints);

        Añadir_Producto.setText("Añadir producto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        Panel_Registro_Venta.add(Añadir_Producto, gridBagConstraints);

        Etiqueta_Cliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Etiqueta_Cliente.setText("Nombre Cliente");
        Etiqueta_Cliente.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        Panel_Registro_Venta.add(Etiqueta_Cliente, gridBagConstraints);

        Etiqueta_Producto.setText("Nombre Producto");
        Etiqueta_Producto.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        Panel_Registro_Venta.add(Etiqueta_Producto, gridBagConstraints);

        Etiqueta_Error_fecha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Etiqueta_Error_fecha.setForeground(new java.awt.Color(204, 0, 0));
        Etiqueta_Error_fecha.setText("Debe introducir una fecha");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        Panel_Registro_Venta.add(Etiqueta_Error_fecha, gridBagConstraints);

        Etiqueta_Error_cantidad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Etiqueta_Error_cantidad.setForeground(new java.awt.Color(204, 0, 0));
        Etiqueta_Error_cantidad.setText("Debe introducir una cantidad válida");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        Panel_Registro_Venta.add(Etiqueta_Error_cantidad, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        Panel_General.add(Panel_Registro_Venta, gridBagConstraints);

        Panel_Detalle_Venta.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Detalle_Venta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalle venta", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        Panel_Detalle_Venta.setLayout(new java.awt.GridBagLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo de barras", "Nombre producto", "Cantidad", "Precio Unitario €", "Tipo de Iva %"
            }
        ));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(2).setMinWidth(15);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(15);
            jTable1.getColumnModel().getColumn(3).setMinWidth(20);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(20);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(5);
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 577;
        gridBagConstraints.ipady = 83;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        Panel_Detalle_Venta.add(jScrollPane1, gridBagConstraints);

        Etiqueta_Error_producto_duplicado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Etiqueta_Error_producto_duplicado.setForeground(new java.awt.Color(204, 0, 0));
        Etiqueta_Error_producto_duplicado.setText("Producto ya añadido a la compra");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 213, 0, 0);
        Panel_Detalle_Venta.add(Etiqueta_Error_producto_duplicado, gridBagConstraints);
        Etiqueta_Error_producto_duplicado.getAccessibleContext().setAccessibleName("");

        Etiqueta_Error_no_seleccion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Etiqueta_Error_no_seleccion.setForeground(new java.awt.Color(204, 0, 0));
        Etiqueta_Error_no_seleccion.setText("No ha seleccionado ningun producto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 205, 0, 0);
        Panel_Detalle_Venta.add(Etiqueta_Error_no_seleccion, gridBagConstraints);

        Etiqueta_Error_Stock.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Etiqueta_Error_Stock.setForeground(new java.awt.Color(204, 0, 0));
        Etiqueta_Error_Stock.setText("No hay suficientes existencias del producto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 205, 0, 0);
        Panel_Detalle_Venta.add(Etiqueta_Error_Stock, gridBagConstraints);

        Espacio.setText("                                                         ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        Panel_Detalle_Venta.add(Espacio, gridBagConstraints);

        Espacio1.setText("                                                         ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        Panel_Detalle_Venta.add(Espacio1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        Panel_General.add(Panel_Detalle_Venta, gridBagConstraints);

        Panel_Importe_Compra.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Importe_Compra.setPreferredSize(new java.awt.Dimension(200, 300));
        java.awt.GridBagLayout Panel_Importe_CompraLayout = new java.awt.GridBagLayout();
        Panel_Importe_CompraLayout.columnWidths = new int[] {0, 6, 0};
        Panel_Importe_CompraLayout.rowHeights = new int[] {0, 8, 0, 8, 0, 8, 0};
        Panel_Importe_Compra.setLayout(Panel_Importe_CompraLayout);

        Boton_Validar_Registro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Boton_Validar_Registro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_validar_compra_venta_2.png"))); // NOI18N
        Boton_Validar_Registro.setText("Validar venta");
        Boton_Validar_Registro.setBorderPainted(false);
        Boton_Validar_Registro.setContentAreaFilled(false);
        Boton_Validar_Registro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Boton_Validar_Registro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        Panel_Importe_Compra.add(Boton_Validar_Registro, gridBagConstraints);

        Etiqueta_IVA.setText("IVA:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        Panel_Importe_Compra.add(Etiqueta_IVA, gridBagConstraints);

        Etiqueta_base_imponible.setText("Base imponible: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        Panel_Importe_Compra.add(Etiqueta_base_imponible, gridBagConstraints);

        Etiqueta_Total.setText("Total:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        Panel_Importe_Compra.add(Etiqueta_Total, gridBagConstraints);

        Importe_Base_Imponible.setText("0 €");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        Panel_Importe_Compra.add(Importe_Base_Imponible, gridBagConstraints);

        Importe_IVA.setText("0 €");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        Panel_Importe_Compra.add(Importe_IVA, gridBagConstraints);

        Importe_Total.setText("0 €");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        Panel_Importe_Compra.add(Importe_Total, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        Panel_General.add(Panel_Importe_Compra, gridBagConstraints);

        getContentPane().add(Panel_General, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario_Registro_Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario_Registro_Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario_Registro_Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario_Registro_Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario_Registro_Venta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Añadir_Producto;
    private javax.swing.JButton Boton_Validar_Registro;
    private javax.swing.JButton Boton_Volver;
    private javax.swing.JLabel Cabecera;
    private javax.swing.JTextField Campo_cantidad;
    private javax.swing.JComboBox<String> Desplegable_Clientes;
    private javax.swing.JComboBox<String> Desplegable_Producto;
    private javax.swing.JButton Eliminar_producto;
    private javax.swing.JLabel Espacio;
    private javax.swing.JLabel Espacio1;
    private javax.swing.JLabel Etiqueta_Cliente;
    private javax.swing.JLabel Etiqueta_Error_Stock;
    private javax.swing.JLabel Etiqueta_Error_cantidad;
    private javax.swing.JLabel Etiqueta_Error_fecha;
    private javax.swing.JLabel Etiqueta_Error_no_seleccion;
    private javax.swing.JLabel Etiqueta_Error_producto_duplicado;
    private javax.swing.JLabel Etiqueta_Espacio;
    private javax.swing.JLabel Etiqueta_IVA;
    private javax.swing.JLabel Etiqueta_Producto;
    private javax.swing.JLabel Etiqueta_Registro_Venta;
    private javax.swing.JLabel Etiqueta_Total;
    private javax.swing.JLabel Etiqueta_base_imponible;
    private javax.swing.JLabel Etiqueta_venta;
    private javax.swing.JLabel Importe_Base_Imponible;
    private javax.swing.JLabel Importe_IVA;
    private javax.swing.JLabel Importe_Total;
    private javax.swing.JLabel JLabel;
    private javax.swing.JPanel Panel_Detalle_Venta;
    private javax.swing.JPanel Panel_General;
    private javax.swing.JPanel Panel_Importe_Compra;
    private javax.swing.JPanel Panel_Registro_Venta;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

     class FondoPanel extends JPanel
   {
           private Image foto;
           
           @Override
           
           public void paint (Graphics g){
           
           foto=new ImageIcon(getClass().getResource("/Imagenes/almacen_2.jpg")).getImage();
               
           g.drawImage(foto, 0, 0,getWidth(),getHeight(), this);
           
           setOpaque(false);
           
           super.paint(g);
           
           }
           
           
           }

    public ArrayList getLista_clientes() {
        return lista_clientes;
    }

   
    public ArrayList getLista_productos() {
        return lista_productos;
    }

    public JButton getAñadir_Producto() {
        return Añadir_Producto;
    }

    public JButton getBoton_Validar_Registro() {
        return Boton_Validar_Registro;
    }

    public JButton getBoton_Volver() {
        return Boton_Volver;
    }

    public JTextField getCampo_cantidad() {
        return Campo_cantidad;
    }

    public JComboBox<String> getDesplegable_Clientes() {
        return Desplegable_Clientes;
    }

    public JComboBox<String> getDesplegable_Producto() {
        return Desplegable_Producto;
    }

    public JButton getEliminar_producto() {
        return Eliminar_producto;
    }

    public JLabel getEtiqueta_Cliente() {
        return Etiqueta_Cliente;
    }

    public JLabel getEtiqueta_Error_Stock() {
        return Etiqueta_Error_Stock;
    }

    public JLabel getEtiqueta_Error_cantidad() {
        return Etiqueta_Error_cantidad;
    }

    public JLabel getEtiqueta_Error_fecha() {
        return Etiqueta_Error_fecha;
    }

    public JLabel getEtiqueta_Error_no_seleccion() {
        return Etiqueta_Error_no_seleccion;
    }

    public JLabel getEtiqueta_Error_producto_duplicado() {
        return Etiqueta_Error_producto_duplicado;
    }

    public JLabel getEtiqueta_Espacio() {
        return Etiqueta_Espacio;
    }

    public JLabel getEtiqueta_IVA() {
        return Etiqueta_IVA;
    }

    public JLabel getEtiqueta_Producto() {
        return Etiqueta_Producto;
    }

    public JLabel getEtiqueta_Registro_Venta() {
        return Etiqueta_Registro_Venta;
    }

    public JLabel getEtiqueta_Total() {
        return Etiqueta_Total;
    }

    public JLabel getEtiqueta_base_imponible() {
        return Etiqueta_base_imponible;
    }

    public JLabel getEtiqueta_venta() {
        return Etiqueta_venta;
    }

    public JLabel getImporte_Base_Imponible() {
        return Importe_Base_Imponible;
    }

    public JLabel getImporte_IVA() {
        return Importe_IVA;
    }

    public JLabel getImporte_Total() {
        return Importe_Total;
    }

    public JDateChooser getjDateChooser1() {
        return jDateChooser1;
    }

    public JTable getjTable1() {
        return jTable1;
    }
    
    
    
    
}
