/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;


import CONTROLADOR.*;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;



/**
 *Esta clase representa los formularios de registro de producto 
 * @author GERMAN
 */


public class Formulario_Registro_Producto extends javax.swing.JFrame {

    
 /**
   * Se obtiene un objeto que encapsula un nuevo formulario de registro de producto 
   */
    
    FondoPanel fondo=new FondoPanel();
    
    boolean nueva_categoria=false;
    
    public Formulario_Registro_Producto() {
        
        this.setContentPane(fondo);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        añade_controladores();
        Etiqueta_error_codigo_de_barras.setVisible(false);
        Etiqueta_error_precio_compra.setVisible(false);
        Etiqueta_error_precio_venta.setVisible(false);
        Etiqueta_error_stock_inicial.setVisible(false);
        Etiqueta_error_producto_duplicado.setVisible(false);
        Etiqueta_error_nombre.setVisible(false);
        Etiqueta_error_categoria_nombre.setVisible(false);
        Etiqueta_error_categoria_duplicada.setVisible(false);
        
        Panel_Seleccione_Categoria.setVisible(true);
        Panel_Nueva_Categoria.setVisible(false);
    }
    
    public void añade_controladores(){
    
    this.addWindowListener(new Controlador_Formulario_Registro_Producto_Inicio());
    Boton_registrar_nuevo_producto.addActionListener(new Controlador_Formulario_Registro_Producto_Validar_Producto());
    Boton_Volver.addActionListener(new Controlador_Formulario_Producto_Abrir());
    Desplegable_Tipo_Categoria.addActionListener(new Controlador_Formulario_Registro_Producto_Desplegable_tipo_categoria());
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Panel_Marco = new javax.swing.JPanel();
        Panel_contenedor = new javax.swing.JPanel();
        Panel_Inferior = new javax.swing.JPanel();
        Boton_Volver = new javax.swing.JButton();
        Boton_registrar_nuevo_producto = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Panel_Cabecera = new javax.swing.JPanel();
        Cabecera = new javax.swing.JLabel();
        Panel_Datos = new javax.swing.JPanel();
        Panel_Izquierdo = new javax.swing.JPanel();
        Panel_General = new javax.swing.JPanel();
        Etiqueta_codigo_de_barras = new javax.swing.JLabel();
        Etiqueta_Nombre = new javax.swing.JLabel();
        Etiqueta_descripcion = new javax.swing.JLabel();
        Etiqueta_Precio_Compra = new javax.swing.JLabel();
        Etiqueta_stock_inicial = new javax.swing.JLabel();
        Etiqueta_tipo_IVA_soportado = new javax.swing.JLabel();
        Etiqueta_Precio_Venta = new javax.swing.JLabel();
        Etiqueta_tipo_IVA_Repercutido = new javax.swing.JLabel();
        tipo_IVA_soportado = new javax.swing.JComboBox<>();
        Texto_codigo_barras = new javax.swing.JTextField();
        tipo_IVA_repercutido = new javax.swing.JComboBox<>();
        texto_stock_inicial = new javax.swing.JTextField();
        texto_nombre = new javax.swing.JTextField();
        texto_precio_compra = new javax.swing.JTextField();
        texto_precio_venta = new javax.swing.JTextField();
        Etiqueta_error_codigo_de_barras = new javax.swing.JLabel();
        Etiqueta_error_precio_compra = new javax.swing.JLabel();
        Etiqueta_error_stock_inicial = new javax.swing.JLabel();
        Etiqueta_error_precio_venta = new javax.swing.JLabel();
        Etiqueta_error_producto_duplicado = new javax.swing.JLabel();
        Etiqueta_error_nombre = new javax.swing.JLabel();
        Etiqueta_Categoría = new javax.swing.JLabel();
        Desplegable_Tipo_Categoria = new javax.swing.JComboBox<>();
        Etiqueta_espacio_1 = new javax.swing.JLabel();
        Etiqueta_espacio_2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Texto_descripcion = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        Panel_Nueva_Categoria = new javax.swing.JPanel();
        Etiqueta_nueva_categoria = new javax.swing.JLabel();
        texto_nueva_categoria = new javax.swing.JTextField();
        Etiqueta_error_categoria_duplicada = new javax.swing.JLabel();
        Etiqueta_error_categoria_nombre = new javax.swing.JLabel();
        Panel_Seleccione_Categoria = new javax.swing.JPanel();
        Etiqueta_Seleccione_Categoría = new javax.swing.JLabel();
        Desplegable_Categoria = new javax.swing.JComboBox<>();
        Panel_Derecho = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0};
        layout.rowHeights = new int[] {0};
        getContentPane().setLayout(layout);

        Panel_Marco.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Marco.setLayout(new java.awt.GridBagLayout());

        Panel_contenedor.setBackground(new java.awt.Color(255, 255, 255));
        Panel_contenedor.setLayout(new java.awt.BorderLayout());

        Panel_Inferior.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Inferior.setPreferredSize(new java.awt.Dimension(760, 123));
        Panel_Inferior.setLayout(new java.awt.BorderLayout());

        Boton_Volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_flecha_izquierda.png"))); // NOI18N
        Boton_Volver.setBorderPainted(false);
        Boton_Volver.setContentAreaFilled(false);
        Boton_Volver.setMargin(new java.awt.Insets(2, 14, 2, 30));
        Boton_Volver.setPreferredSize(new java.awt.Dimension(80, 40));
        Panel_Inferior.add(Boton_Volver, java.awt.BorderLayout.EAST);

        Boton_registrar_nuevo_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_validar_compra_venta.png"))); // NOI18N
        Boton_registrar_nuevo_producto.setText("Registrar nuevo producto");
        Boton_registrar_nuevo_producto.setBorderPainted(false);
        Boton_registrar_nuevo_producto.setContentAreaFilled(false);
        Boton_registrar_nuevo_producto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Boton_registrar_nuevo_producto.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Boton_registrar_nuevo_producto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Panel_Inferior.add(Boton_registrar_nuevo_producto, java.awt.BorderLayout.CENTER);

        jLabel3.setText("                          ");
        Panel_Inferior.add(jLabel3, java.awt.BorderLayout.WEST);

        Panel_contenedor.add(Panel_Inferior, java.awt.BorderLayout.SOUTH);

        Panel_Cabecera.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Cabecera.setLayout(new java.awt.BorderLayout());

        Cabecera.setBackground(new java.awt.Color(255, 255, 255));
        Cabecera.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        Cabecera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cabecera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_software_gestor_tienda_pequeño_min.png"))); // NOI18N
        Cabecera.setText("Software Gestor de Tienda");
        Cabecera.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Cabecera.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Cabecera.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Panel_Cabecera.add(Cabecera, java.awt.BorderLayout.CENTER);

        Panel_contenedor.add(Panel_Cabecera, java.awt.BorderLayout.NORTH);

        Panel_Datos.setLayout(new java.awt.BorderLayout());

        Panel_Izquierdo.setLayout(new java.awt.BorderLayout());
        Panel_Datos.add(Panel_Izquierdo, java.awt.BorderLayout.WEST);

        Panel_General.setBackground(new java.awt.Color(255, 255, 255));
        Panel_General.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nuevo producto\n", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        Panel_General.setLayout(new java.awt.GridBagLayout());

        Etiqueta_codigo_de_barras.setText("Codigo de barras");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(42, 72, 0, 0);
        Panel_General.add(Etiqueta_codigo_de_barras, gridBagConstraints);

        Etiqueta_Nombre.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 72, 0, 0);
        Panel_General.add(Etiqueta_Nombre, gridBagConstraints);

        Etiqueta_descripcion.setText("Descripcion");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 72, 0, 0);
        Panel_General.add(Etiqueta_descripcion, gridBagConstraints);

        Etiqueta_Precio_Compra.setText("Precio de compra");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 72, 0, 0);
        Panel_General.add(Etiqueta_Precio_Compra, gridBagConstraints);

        Etiqueta_stock_inicial.setText("Stock inicial");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 72, 0, 0);
        Panel_General.add(Etiqueta_stock_inicial, gridBagConstraints);

        Etiqueta_tipo_IVA_soportado.setText("Tipo de IVA soportado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 72, 0, 0);
        Panel_General.add(Etiqueta_tipo_IVA_soportado, gridBagConstraints);

        Etiqueta_Precio_Venta.setText("Precio de venta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 72, 0, 0);
        Panel_General.add(Etiqueta_Precio_Venta, gridBagConstraints);

        Etiqueta_tipo_IVA_Repercutido.setText("Tipo de IVA repercutido");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 72, 0, 0);
        Panel_General.add(Etiqueta_tipo_IVA_Repercutido, gridBagConstraints);

        tipo_IVA_soportado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "21%", "10%", "4%" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        Panel_General.add(tipo_IVA_soportado, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 116;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(39, 20, 0, 0);
        Panel_General.add(Texto_codigo_barras, gridBagConstraints);

        tipo_IVA_repercutido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "21%", "10%", "4%" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 6, 0);
        Panel_General.add(tipo_IVA_repercutido, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 48;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 0);
        Panel_General.add(texto_stock_inicial, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 116;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        Panel_General.add(texto_nombre, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 62;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        Panel_General.add(texto_precio_compra, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 62;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 0);
        Panel_General.add(texto_precio_venta, gridBagConstraints);

        Etiqueta_error_codigo_de_barras.setText("Debe introducir un numero de entre 7 y 10 digitos");
        Etiqueta_error_codigo_de_barras.setPreferredSize(new java.awt.Dimension(300, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 62;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(42, 10, 0, 0);
        Panel_General.add(Etiqueta_error_codigo_de_barras, gridBagConstraints);

        Etiqueta_error_precio_compra.setText("Debe introducir un numero decimal (máximo 2 decimales)");
        Etiqueta_error_precio_compra.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 10, 0, 0);
        Panel_General.add(Etiqueta_error_precio_compra, gridBagConstraints);

        Etiqueta_error_stock_inicial.setText("Debe introducir un numero entero");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 10, 0, 0);
        Panel_General.add(Etiqueta_error_stock_inicial, gridBagConstraints);

        Etiqueta_error_precio_venta.setText("Debe introducir un numero decimal (máximo 2 decimales)");
        Etiqueta_error_precio_venta.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 10, 0, 0);
        Panel_General.add(Etiqueta_error_precio_venta, gridBagConstraints);

        Etiqueta_error_producto_duplicado.setText("Producto ya existente");
        Etiqueta_error_producto_duplicado.setPreferredSize(new java.awt.Dimension(20, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 58;
        gridBagConstraints.ipady = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 10, 0, 0);
        Panel_General.add(Etiqueta_error_producto_duplicado, gridBagConstraints);

        Etiqueta_error_nombre.setText("Debe introducir un nombre entre 1 y 15 caracteres");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 10, 0, 0);
        Panel_General.add(Etiqueta_error_nombre, gridBagConstraints);

        Etiqueta_Categoría.setText("Categoría");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(43, 72, 0, 0);
        Panel_General.add(Etiqueta_Categoría, gridBagConstraints);

        Desplegable_Tipo_Categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Categorías disponibles", "Nueva Categoría" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 20, 0, 0);
        Panel_General.add(Desplegable_Tipo_Categoria, gridBagConstraints);

        Etiqueta_espacio_1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Etiqueta_espacio_1.setText("                                                                                                                     ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(42, 10, 0, 63);
        Panel_General.add(Etiqueta_espacio_1, gridBagConstraints);

        Etiqueta_espacio_2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Etiqueta_espacio_2.setText("                                                                                                                     ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 10, 0, 63);
        Panel_General.add(Etiqueta_espacio_2, gridBagConstraints);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Texto_descripcion.setColumns(20);
        Texto_descripcion.setRows(5);
        Texto_descripcion.setPreferredSize(new java.awt.Dimension(6, 20));
        jScrollPane2.setViewportView(Texto_descripcion);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 40));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 0);
        Panel_General.add(jPanel1, gridBagConstraints);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_Nueva_Categoria.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Nueva_Categoria.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nueva Categoria", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        Panel_Nueva_Categoria.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Etiqueta_nueva_categoria.setText("Nombre categoría: ");
        Panel_Nueva_Categoria.add(Etiqueta_nueva_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));
        Panel_Nueva_Categoria.add(texto_nueva_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 130, -1));

        Etiqueta_error_categoria_duplicada.setText("Categoría ya existente");
        Panel_Nueva_Categoria.add(Etiqueta_error_categoria_duplicada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        Etiqueta_error_categoria_nombre.setText("Nombre incorrecto");
        Panel_Nueva_Categoria.add(Etiqueta_error_categoria_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jPanel2.add(Panel_Nueva_Categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 80));

        Panel_Seleccione_Categoria.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Seleccione_Categoria.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Categoría existente ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        Panel_Seleccione_Categoria.setLayout(new java.awt.GridBagLayout());

        Etiqueta_Seleccione_Categoría.setText("Seleccione categoría:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        Panel_Seleccione_Categoria.add(Etiqueta_Seleccione_Categoría, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        Panel_Seleccione_Categoria.add(Desplegable_Categoria, gridBagConstraints);

        jPanel2.add(Panel_Seleccione_Categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 80));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 45, 0, 0);
        Panel_General.add(jPanel2, gridBagConstraints);

        Panel_Datos.add(Panel_General, java.awt.BorderLayout.CENTER);

        Panel_Derecho.setLayout(new java.awt.BorderLayout());
        Panel_Datos.add(Panel_Derecho, java.awt.BorderLayout.EAST);

        Panel_contenedor.add(Panel_Datos, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        Panel_Marco.add(Panel_contenedor, gridBagConstraints);

        getContentPane().add(Panel_Marco, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
 
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario_Registro_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario_Registro_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario_Registro_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario_Registro_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario_Registro_Producto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Volver;
    private javax.swing.JButton Boton_registrar_nuevo_producto;
    private javax.swing.JLabel Cabecera;
    private javax.swing.JComboBox<String> Desplegable_Categoria;
    private javax.swing.JComboBox<String> Desplegable_Tipo_Categoria;
    private javax.swing.JLabel Etiqueta_Categoría;
    private javax.swing.JLabel Etiqueta_Nombre;
    private javax.swing.JLabel Etiqueta_Precio_Compra;
    private javax.swing.JLabel Etiqueta_Precio_Venta;
    private javax.swing.JLabel Etiqueta_Seleccione_Categoría;
    private javax.swing.JLabel Etiqueta_codigo_de_barras;
    private javax.swing.JLabel Etiqueta_descripcion;
    private javax.swing.JLabel Etiqueta_error_categoria_duplicada;
    private javax.swing.JLabel Etiqueta_error_categoria_nombre;
    private javax.swing.JLabel Etiqueta_error_codigo_de_barras;
    private javax.swing.JLabel Etiqueta_error_nombre;
    private javax.swing.JLabel Etiqueta_error_precio_compra;
    private javax.swing.JLabel Etiqueta_error_precio_venta;
    private javax.swing.JLabel Etiqueta_error_producto_duplicado;
    private javax.swing.JLabel Etiqueta_error_stock_inicial;
    private javax.swing.JLabel Etiqueta_espacio_1;
    private javax.swing.JLabel Etiqueta_espacio_2;
    private javax.swing.JLabel Etiqueta_nueva_categoria;
    private javax.swing.JLabel Etiqueta_stock_inicial;
    private javax.swing.JLabel Etiqueta_tipo_IVA_Repercutido;
    private javax.swing.JLabel Etiqueta_tipo_IVA_soportado;
    private javax.swing.JPanel Panel_Cabecera;
    private javax.swing.JPanel Panel_Datos;
    private javax.swing.JPanel Panel_Derecho;
    private javax.swing.JPanel Panel_General;
    private javax.swing.JPanel Panel_Inferior;
    private javax.swing.JPanel Panel_Izquierdo;
    private javax.swing.JPanel Panel_Marco;
    private javax.swing.JPanel Panel_Nueva_Categoria;
    private javax.swing.JPanel Panel_Seleccione_Categoria;
    private javax.swing.JPanel Panel_contenedor;
    private javax.swing.JTextField Texto_codigo_barras;
    private javax.swing.JTextArea Texto_descripcion;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField texto_nombre;
    private javax.swing.JTextField texto_nueva_categoria;
    private javax.swing.JTextField texto_precio_compra;
    private javax.swing.JTextField texto_precio_venta;
    private javax.swing.JTextField texto_stock_inicial;
    private javax.swing.JComboBox<String> tipo_IVA_repercutido;
    private javax.swing.JComboBox<String> tipo_IVA_soportado;
    // End of variables declaration//GEN-END:variables

    public JTextField getTexto_codigo_barras() {
        return Texto_codigo_barras;
    }

    public JTextField getTexto_nombre() {
        return texto_nombre;
    }

    public JTextField getTexto_precio_compra() {
        return texto_precio_compra;
    }

    public JTextField getTexto_precio_venta() {
        return texto_precio_venta;
    }

    public JTextField getTexto_stock_inicial() {
        return texto_stock_inicial;
    }

    public JLabel getEtiqueta_error_codigo_de_barras() {
        return Etiqueta_error_codigo_de_barras;
    }

    public JLabel getEtiqueta_error_precio_compra() {
        return Etiqueta_error_precio_compra;
    }

    public JLabel getEtiqueta_error_precio_venta() {
        return Etiqueta_error_precio_venta;
    }

    public JLabel getEtiqueta_error_stock_inicial() {
        return Etiqueta_error_stock_inicial;
    }

    public JTextArea getTexto_descripcion() {
        return Texto_descripcion;
    }

    public JComboBox<String> getTipo_IVA_repercutido() {
        return tipo_IVA_repercutido;
    }

    public JComboBox<String> getTipo_IVA_soportado() {
        return tipo_IVA_soportado;
    }

    public JLabel getEtiqueta_error_producto_duplicado() {
        return Etiqueta_error_producto_duplicado;
    }

    public JLabel getEtiqueta_error_nombre() {
        return Etiqueta_error_nombre;
    }

    public JComboBox<String> getDesplegable_Categoria() {
        return Desplegable_Categoria;
    }

    public JPanel getPanel_Nueva_Categoria() {
        return Panel_Nueva_Categoria;
    }

    public JPanel getPanel_Seleccione_Categoria() {
        return Panel_Seleccione_Categoria;
    }

    public JTextField getTexto_nueva_categoria() {
        return texto_nueva_categoria;
    }

    public boolean Nueva_categoria() {
        return nueva_categoria;
    }

    public void setNueva_categoria(boolean nueva_categoria) {
        this.nueva_categoria = nueva_categoria;
    }

    public JLabel getEtiqueta_error_categoria_duplicada() {
        return Etiqueta_error_categoria_duplicada;
    }

    public JLabel getEtiqueta_error_categoria_nombre() {
        return Etiqueta_error_categoria_nombre;
    }
    
    
    
    
     class FondoPanel extends JPanel
   {
           private Image foto;
           
           @Override
           
           public void paint (Graphics g){
           
           foto=new ImageIcon(getClass().getResource("/Imagenes/almacen_2.jpg")).getImage();
               
           g.drawImage(foto, 0, 0,getWidth(),getHeight(), this);
           
           setOpaque(false);
           
           super.paint(g);
           
           }
           
           
           }
    

}

